SELECT
    DATE_FORMAT(SALES_DATE,"%Y-%m-%d") AS SALES_DATE
     ,PRODUCT_ID
     ,USER_ID
     ,SALES_AMOUNT
FROM ONLINE_SALE
WHERE
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') >='2022-03-01' AND DATE_FORMAT(SALES_DATE, '%Y-%m-%d') <'2022-04-01'

UNION ALL
SELECT
    DATE_FORMAT(SALES_DATE,"%Y-%m-%d") AS SALES_DATE
     ,PRODUCT_ID
     , null AS user_id
     , SALES_AMOUNT
FROM OFFLINE_SALE
WHERE
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') >='2022-03-01' AND DATE_FORMAT(SALES_DATE, '%Y-%m-%d') <'2022-04-01'
ORDER BY
    SALES_DATE, PRODUCT_ID, user_id