SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * BS.SALES) as TOTAL_SALES
FROM
    BOOK as B
JOIN AUTHOR as A ON
    A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES as BS ON
    BS.BOOK_ID = B.BOOK_ID
WHERE
    DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = "2022-01"
GROUP BY
    A.AUTHOR_NAME, B.CATEGORY
ORDER BY
    A.AUTHOR_ID, B.CATEGORY desc