SELECT
    MONTH(START_DATE) as MONTH,
    C2.CAR_ID,
    count(*) as RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY as C1,
    (SELECT
    CAR_ID
    FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
    START_DATE BETWEEN '2022-08-01' and '2022-10-31'
    GROUP BY
    CAR_ID HAVING count(*) >= 5) as C2
WHERE
    C1.CAR_ID = C2.CAR_ID
  AND
    START_DATE BETWEEN '2022-08-01' and '2022-10-31'
GROUP BY
    MONTH(START_DATE), C2.CAR_ID
HAVING count(*) > 0
ORDER BY
    MONTH(START_DATE), C2.CAR_ID desc